#!/usr/bin/env bash
# Auto-generated by Phoenix v5 receipts framework.
# Claim:    OpenEnv Arena leaderboard ships with 6 baseline rows (MaskablePPO at top)
# Expected: '6 MaskablePPO' (regex)
# Hardware at last run: NVIDIA GeForce RTX 4080 Laptop GPU 11GB VRAM
# Runtime:  0.13s
set -euo pipefail
echo "[V5_Arena_baseline_leaderboard] command:"
echo '> python -m ShAuRyA_Phoenix.arena.leaderboard'
python -m ShAuRyA_Phoenix.arena.leaderboard
echo
echo "[V5_Arena_baseline_leaderboard] extraction:"
echo '> python -c "import json; b=json.load(open(r\"ShAuRyA_Phoenix/experiments/arena/leaderboard.json\")); print(b[\"n_baselines\"], b[\"rows\"][0][\"policy_name\"])"'
python -c "import json; b=json.load(open(r\"ShAuRyA_Phoenix/experiments/arena/leaderboard.json\")); print(b[\"n_baselines\"], b[\"rows\"][0][\"policy_name\"])"
echo
echo "[V5_Arena_baseline_leaderboard] expected: 6 MaskablePPO"
echo "[V5_Arena_baseline_leaderboard] comparator: regex"
