#!/usr/bin/env bash
# Auto-generated by Phoenix v5 receipts framework.
# Claim:    Autoresearch S3 accepted with CI95 lower delta >= +0.05 over S2 (final best)
# Expected: '0.05' (>=)
# Hardware at last run: NVIDIA GeForce RTX 4080 Laptop GPU 11GB VRAM
# Runtime:  0.37s
set -euo pipefail
echo "[V5_Autoresearch_CI95_lift] command:"
echo '> python -m ShAuRyA_Phoenix.autoresearch_fixed.rebuild_state'
python -m ShAuRyA_Phoenix.autoresearch_fixed.rebuild_state
echo
echo "[V5_Autoresearch_CI95_lift] extraction:"
echo '> python -c "import json; s=json.load(open(r\"ShAuRyA_Phoenix/autoresearch_fixed/state.json\")); h=[x for x in s[\"history\"] if x[\"experiment_name\"]==\"s3_curriculum_learning\"][0]; print(h[\"delta_ci95_lower\"])"'
python -c "import json; s=json.load(open(r\"ShAuRyA_Phoenix/autoresearch_fixed/state.json\")); h=[x for x in s[\"history\"] if x[\"experiment_name\"]==\"s3_curriculum_learning\"][0]; print(h[\"delta_ci95_lower\"])"
echo
echo "[V5_Autoresearch_CI95_lift] expected: 0.05"
echo "[V5_Autoresearch_CI95_lift] comparator: >="
